### ISSUE TITLE
Backend: Rework Plugin Settings

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#11]
* check current implementation 
  * enable overrrides
  * output

see: [Plugin Settings](https://github.com/wielebenwir/commons-booking-2/wiki/Plugin-Settings)

- [x] add message "saved"
- [x] add timeframe options call

**Comment by anewholm** [comment]
i have split the various menu items in to separate files now:
admin/options_page.php is the options area
currently it just shows all the advanced menu items for accessing the whole advanced data structures
would be good to retain this somewhere for debugging purposes

**Comment by flegfleg** [comment]
@anewholm you made some changes to the settings, no? what is the status here?
