### ISSUE TITLE
If the item changes location half way through the month, what is displayed on item P/R calendar view? All opening times for All locations need to be shown?

### ISSUE THREAD

**Issue by anewholm** [wielebenwir/commons-booking-2#124]

**Comment by flegfleg** [comment]
1. during one availability, items can not change location.
2. management calendar shows only 1 availability 
3. availabilities should not overlap

on the front end, multiple availabilities for an item are shown as single calendars, one after the other. 

closing this, if i misunderstood feel free to re-open.
