### ISSUE TITLE
popup header with appropriate colour and labels. save all/from/this as "bottom tabs". finish save just this event to create a new period.

### ISSUE THREAD

**Issue by anewholm** [wielebenwir/commons-booking-2#190]
save all/from/this as bottom tabs.
finish save just this event to create a *new* period.

**Comment by anewholm** [comment]
![image](https://user-images.githubusercontent.com/708045/56494350-383e9700-64f2-11e9-8ec3-0b8df545e47b.png)

**Comment by flegfleg** [comment]
hi @anewholm, 
here is my take. note that the editor is missing some borders, we use the default meta box style. 
let me know what you think. 



![management-calendar-popup-expl-box](https://user-images.githubusercontent.com/4009931/56507820-d8141900-6522-11e9-81be-9507bcc70e74.png)

![management-calendar-popup-expl-1](https://user-images.githubusercontent.com/4009931/56507821-d8acaf80-6522-11e9-8476-94466018047e.png)

![management-calendar-popup-expl-2](https://user-images.githubusercontent.com/4009931/56507825-d8acaf80-6522-11e9-82d5-4d6670c95289.png)

![management-calendar-popup-expl-3](https://user-images.githubusercontent.com/4009931/56507824-d8acaf80-6522-11e9-88e1-e95c06c2e566.png)

![management-calendar-popup-expl-4](https://user-images.githubusercontent.com/4009931/56507823-d8acaf80-6522-11e9-9f31-78e9f12cc7db.png)

![management-calendar-popup-expl-4-after-save](https://user-images.githubusercontent.com/4009931/56507822-d8acaf80-6522-11e9-8884-f7dc3f5dcf7e.png)
