### ISSUE TITLE
Frontend: Reworks bookings Screen 

### ISSUE THREAD

**Issue by anewholm** [wielebenwir/commons-booking-2#243]
- [x] Block: booked periods 
- [x] Pickup window, return window (periods) 
- [x] Block: Location contact information
- [x] Message: confirmed/needs confirmation
- [x] make the currrent booking status (needs confirmation, needs approval, confiremd) more  obvious (different class, yellow message/ green  ✅message)

**Comment by flegfleg** [comment]
yes, it totally should :)
