### ISSUE TITLE
Backend: Plugin Menu

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#43]
## Wordpress Menu

* **Dashboard**
    * CB-Booking-Admin-Widget? *
* ....
* **CommonsBooking**
    * **Dashboard** should give a bird's eye view of all items/availabilities *
        * Items List with availability (item has an "active" timeframe attached – yes/no) 
        * Locations List
        * Bookings List
        * Current bookings list
    * **Items** (WP Admin table with column "availability" to add/edit timeframes)
    * **Locations** (WP Admin table with column "address")
    * **Bookings** (WP Admin table with column WP user name)
* **Settings**
    * ....
    * **CommonsBooking**

_*not for 2.0_

## Concept

* The "_timeframes_" concept is not very intuitive, and not a lot of items change their location. so my plan is to let people create _availability_ for _items_. user flow: go to items, see all items in a table filterable (by if they have an active timeframe attached or not), create/edit/add "availabilities"/"timeframes" there
* Similarly, for _booking codes_: The current (cb0.9) menu entry with a table view of all codes does not make sense. My proposal: No "codes" menu entry, users go to items, click the availability, see the calendar with the codes (and bookings). 

* _Period types_ should go into the plugin settings menu (or an "advanced" section)
* _Holidays_ (choosing a holiday provider, see #2 ) should go into the plugin settings menu, list of holidays like under the current menu entry is useful only for debugging. 
* _Opening hours_ should be edited from locations-single-edit. 
* _Repairs_ are a special use case, not a feature cb2 should provide out-of-the-box

**Comment by anewholm** [comment]
The top level menu needs a page. If it is not the DashBoard (nto for 2.0), then what is it?
Should we have a simple DashBoard for 2.0?
Creating it should be easy: everything is posts, presenting them is quick...

**Comment by flegfleg** [comment]
That would be great.
Will you move the menu out of framework to /admin/admin-enque or shall I do it

**Comment by flegfleg** [comment]
i think we should add a dedicated "all availabilities calendar" entry in the plugin menu, under dashboard. 

any preferences about the naming? 

* "Calendar"
* "Availabilities"
* "Management"
* ?
