### ISSUE TITLE
"All day" slots not reflected on the front end

### ISSUE THREAD

**Issue by anewholm** [wielebenwir/commons-booking-2#437]
- "All day" is shown in backend (correctly)
- On the front end, the hours are shown (should be: same as backend, "All day")

<img width="1234" alt="Bildschirmfoto 2020-01-05 um 16 16 52" src="https://user-images.githubusercontent.com/4009931/71782128-0e24fa80-2fd7-11ea-970b-7651b8669257.png">

https://github.com/wielebenwir/commons-booking-2/blob/3b40ce2cd061318b9e30564fd970f3e367a7848e/framework/CB2_Query/CB2_PeriodInst.php#L533

**Comment by flegfleg** [comment]
This is the "daily slots" option, isn't  it?
I would put it in the wizard:

* Opening hours
* Hourly slots
* Daily (available if no opening hours set up)
* Custom (available if no opening hours set up)
