### ISSUE TITLE
Delete unconfirmed bookings after a certain amount of time (e.g:  1h)

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#473]
## implement setting 

**text**
"automatically delete unconfirmed bookings after X Minutes" [_____] 
**description**
"Leave blank to keep unconfirmed bookings. You will have to manually delete these so the item is available again."

## implement cron

**Comment by markus-mw** [comment]
Created branch for this issue: feature/issue-473

**Comment by markus-mw** [comment]
@flegfleg Is there any automatism to remove timeperiods for locations when they got deleted?

**Comment by flegfleg** [comment]
Hi, it is on the radar, issue: #440
this is important for the API, so we need to discuss this with @christianvoigt
