### ISSUE TITLE
Is CB2 production ready?

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commons-booking-2#502]
Hi,

I am in research if CB2 is considered as stable at this moment. This question addresses mainly the maintainers and other initiatives who are already using CB2 in production.

What are your experiences?

Background:
We, meaning the fjordbeweger.de from Flensburg, using currently CB1 and it just works. Although we looking for some of the new features from CB2 like hourly booking as this was requested a lot from our users. My motivation is to get some insights in the state of the project which I can report to the city representatives, users and the ADFC when this topic is discussed the next time.

Thanks in advance

**Comment by flegfleg** [comment]
Hi Stefan, 
we are still working on it, but expect a release soon. 

Best!
