### ISSUE TITLE
Backend Bookings list rework

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#509]
Die Buchungsliste im Admin-Backend soll überarbeitet werden.

Aktuelle Ansicht:
![image](https://user-images.githubusercontent.com/12683634/72688993-f2f4d780-3b0c-11ea-93ba-8235a29b0bb1.png)

Gewünscht neue Ansicht:
siehe Miro-Screen mit Anmerkungen:
https://miro.com/app/board/o9J_kxXD9Fk=/?moveToWidget=3074457346733722586
Die Anpassungen sind als "comments" in Miro beschrieben. Siehe Pins auf dem Screen.
![image](https://user-images.githubusercontent.com/12683634/72689122-5b908400-3b0e-11ea-83e4-96e058d75c80.png)

Eine Übersicht der Comments kann über die Leiste unten links eingeblendet werden:
![image](https://user-images.githubusercontent.com/12683634/72689079-dd33e200-3b0d-11ea-8e48-dc06b4af7244.png)

_related issues:_ #486, #488

**Comment by markus-mw** [comment]
unconfirmed bookings aus liste entfernen

**Comment by flegfleg** [comment]
Hi @markus-mw , 
looking good, but: 
- [ ] The cancel button is missing
- [ ] sorting by loc, item, user (see: screenshot) results in white screen

<img width="1011" alt="Bildschirmfoto 2020-02-27 um 09 36 22" src="https://user-images.githubusercontent.com/4009931/75426310-b5be0980-5944-11ea-8cdc-e56a32ddf15a.png">

**Comment by markus-mw** [comment]
The cancel/trash option is now available at the user column.
sorting should be working now

**Comment by hanneskasimir** [comment]
Seite sieht schön aufgeräumt aus.
nur oben ist noch ein Dropdown "all dates" mit einem Button "filter".  https://miro.com/app/board/o9J_kv8Db5U=/?moveToWidget=3074457347295087861
Wenn ich hier etwas ändere, dann komm ich auf eine komplett weiße Seite ohne Fehlermeldungen.

**Comment by markus-mw** [comment]
@hanneskasimir : Ich schau mir das direkt mal an.

**Comment by markus-mw** [comment]
@flegfleg @hanneskasimir : Die Filterung erzeugt einfach keine Rückgabe. Da müsste ich tiefer graben, warum da nichts passiert. Wollen wir das Thema erstmal schieben und die Filterung ausblenden?

**Comment by hanneskasimir** [comment]
Ja, bitte erstmal ausblenden

**Comment by farbschein** [comment]
Wird in hide filter for booking-list #595 bearbeitet.
