### ISSUE TITLE
Fatal error on plugin activation on clean wp install

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#523]
* tested with WP 5.2.3
* Can reproduce with a0253738d9c0872aab69220b3f1acd25dbb66d58
* Second activation is successful

**Comment by anewholm** [comment]
I have an error on activation: output generated during activation. I have never managed to hunt down where the output is coming from. I hacked core WP to show the output but was still none the wiser.

Is this the same error? Can you send a screen shot or details of the error?

**Comment by anewholm** [comment]
Given my imminent lack of time, and that this error is not specific to the CB2 infrastructure, it is best dealt with by someone else I suggest...

**Comment by flegfleg** [comment]
> Is this the same error? Can you send a screen shot or details of the error?

<img width="989" alt="Bildschirmfoto 2020-02-03 um 14 18 41" src="https://user-images.githubusercontent.com/4009931/73656281-1896ea80-4690-11ea-8686-695cd0ee3e55.png">

**Comment by flegfleg** [comment]
not "unexpected output", fatal error & the plugin fails to activate

**Comment by flegfleg** [comment]
> and that this error is not specific to the CB2 infrastructure, 

how do you know that? It would be great if you can look into it, Markus is busy on other tasks.

**Comment by flegfleg** [comment]
I could activate the plugin without problems on the dev server.  @farbschein

**Comment by markus-mw** [comment]
Me, too. The error occured only when the composer install wasn't done before.

**Comment by farbschein** [comment]
@markus-mw is this something that can be fixed / controlled by the plugin itself? Or has the user something to configure on his webserver?

**Comment by flegfleg** [comment]
> @markus-mw is this something that can be fixed / controlled by the plugin itself? Or has the user something to configure on his webserver?

No, non-devs will not have to use composer or configure anything. 

We zip the plugin with all the (non-dev-related) dependencies.

**Comment by flegfleg** [comment]
Fatal error happens only if WP_DEBUG is ON.

**Comment by flegfleg** [comment]
@farbschein @hanneskasimir im nicht debug-modus kann das Plugin ohne Probleme aktiviert werden. Issue zurückstellen?

**Comment by hanneskasimir** [comment]
klingt gut für mich.

**Comment by farbschein** [comment]
@flegfleg @markus-mw 
I made a fresh install on my local system and got the following error on activation:

`( ! ) Warning: require_once(C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2/framework/includes/lib/cmb2/init.php): failed to open stream: No such file or directory in C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\admin\includes\CB2_Metaboxes.php on line 24
Call Stack
#	Time	Memory	Function	Location
1	0.0004	412984	{main}( )	...\plugins.php:0
2	0.6959	8452640	plugin_sandbox_scrape( )	...\plugins.php:175
3	0.6961	8453696	include( 'C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\commons-booking-2.php' )	...\plugin.php:2223
4	0.6963	8454368	require_once( 'C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\framework\CB2_framework.php' )	...\commons-booking-2.php:41
5	0.6963	8454928	require_once( 'C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\admin\includes\CB2_Metaboxes.php' )	...\CB2_framework.php:17
6	0.6963	8454928	CB2_Metaboxes::factory( )	...\CB2_Metaboxes.php:48
7	0.6963	8454968	CB2_Metaboxes->__construct( )	...\CB2_Metaboxes.php:45

( ! ) Fatal error: require_once(): Failed opening required 'C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2/framework/includes/lib/cmb2/init.php' (include_path='.;C:\php\pear') in C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\admin\includes\CB2_Metaboxes.php on line 24
Call Stack
#	Time	Memory	Function	Location
1	0.0004	412984	{main}( )	...\plugins.php:0
2	0.6959	8452640	plugin_sandbox_scrape( )	...\plugins.php:175
3	0.6961	8453696	include( 'C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\commons-booking-2.php' )	...\plugin.php:2223
4	0.6963	8454368	require_once( 'C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\framework\CB2_framework.php' )	...\commons-booking-2.php:41
5	0.6963	8454928	require_once( 'C:\wamp64\www\commonsbooking\01\wordpress\wp-content\plugins\commons-booking-2\admin\includes\CB2_Metaboxes.php' )	...\CB2_framework.php:17
6	0.6963	8454928	CB2_Metaboxes::factory( )	...\CB2_Metaboxes.php:48
7	0.6963	8454968	CB2_Metaboxes->__construct( )	...\CB2_Metaboxes.php:45`

I could'nt find 
`commons-booking-2/framework/includes/lib/cmb2/init.php`
in the file directory. 
Furthermode the whole directory .../includes/lib is not available?
could this cause the error?

**Comment by flegfleg** [comment]
Huhu @farbschein , everything under /lib/ is managed by composer. Check the readme for the install procedure.

**Comment by farbschein** [comment]
@flegfleg thanks. i'm still learning and managed to install composer. Now it works ;-)
