### ISSUE TITLE
Automatische Zuordnung zu My default location hat nicht funktioniert, wie nach Installtion in der Plugin-Liste angepriesen. ggf. Hinweis löschen?

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commons-booking-2#542]

**Comment by flegfleg** [comment]
Am Anfang wird nur gesagt `"We created a default location for you"`, meinst du das? Die wird auch erstellt in meinen Tests.

**Comment by hanneskasimir** [comment]
ja, und dann stand da noch dabei, dass die ersten Items automatisch dieser location zugeordnet werden. das ist aber nicht passiert.
