### ISSUE TITLE
Backend/Bookings/Detailseite: Detailseite entfernern

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commons-booking-2#545]
Aus der Backend/Bookings/Liste soll kein Link mehr zu Booking-Detailansicht führen. Die Detailseite wird deaktiviert.

**Comment by flegfleg** [comment]
da ich nicht weiss wann/ob wir mit der Buchungsliste fertig werden,  hab ich die Buchungsdetail Seite CSS überarbeitet.  So haben wir zumindest eine Ansicht.
