### ISSUE TITLE
(multi-user only) Error on Items page

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#551]
- [ ] If logged in as `contributer` (WP role), items list throws error 

---- 

First, visit your website (http://cb2.test/) and check for any visible issues. Next, visit the page where the error was caught (http://cb2.test/wp-admin/admin.php?page=cb2-items) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

http://cb2.test/wp-login.php?action=enter_recovery_mode&rm_token=xxZGrXhX81xMjuUJVxEVOY&rm_key=WnzQA5iGHUNHzn6zSFaRm6

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3.2
Current theme: Twenty Twenty (version 1.0)
Current plugin: CommonsBooking 2 (version 2.0.0)
PHP version 7.2.13

Error Details
=============
An error of type E_ERROR was caused in line 916 of the file /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-content/plugins/commons-booking-2/framework/CB2_Query/CB2_PeriodEntity.php. Error message: Uncaught Error: Call to a member function usage_multiple() on null in /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-content/plugins/commons-booking-2/framework/CB2_Query/CB2_PeriodEntity.php:916
Stack trace:
#0 /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-content/plugins/commons-booking-2/framework/CB2_Query/WP_Query_integration.php(285): CB2_PeriodEntity->user_has_cap('edit_others_pos...', 'edit_post', NULL, NULL)
#1 /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-includes/class-wp-hook.php(290): cb2_user_has_cap(Array, Array, Array)
#2 /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#3 /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-includes/class-wp-user.php(780): apply_filters('user_has_cap', Array, Array, Array, Object(WP_User))
#4 /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-includes/capabilities.php(658): WP_User->has_cap('edit_post', 10000001)
#5 /Users/fleg/WorkBench/3 DEV/Apache/cb2/wp-content/plugins/commons-booking-2/framework/CB2_Query/CB2_PostNavigator.php(1182

**Comment by christianvoigt** [comment]
Why logged in as "Contributor"? I thought on a multi-user site bike owners will be "authors".

**Comment by christianvoigt** [comment]
I get the same error when logged in as "author". Also, I see the "Kasimir" bike on the backend calendar, even though the "author" user does not own it (or its location).

**Comment by christianvoigt** [comment]
Hi @anewholm  & @flegfleg,

I just pulled master after aad5df52eab451a48da6f339fd3ee42e6f7c6f75 but I still get an "usage_multiple()" error if I log in as author and click on "Items". The error occurs in the "Locations" column. Do I have to reinstall the database or should this work without a reinstall?

Also, please clarify which user roles to use: Should we use "author" or "cb2_contributor" on a multi-user page.

Currently in my installation, authors who have not created a bike will still be able to see them under "Items" and in the "Calendar". This is not the required behavior. Authors should only see their own bikes and locations in the Wordpress backend.

**Comment by flegfleg** [comment]
> I just pulled master after aad5df5 but I still get an "usage_multiple()" error if I log in as author and click on "Items". The error occurs in the "Locations" column. Do I have to reinstall the database or should this work without a reinstall?

works for me, i would try a reinstall

**Comment by christianvoigt** [comment]
Have you tested it as "author" or as "cb2_contributor"? Please clarify which user role to use.

**Comment by flegfleg** [comment]
> Have you tested it as "author" or as "cb2_contributor"? Please clarify which user role to use.

I just realised i tested the "author" role

**Comment by christianvoigt** [comment]
I reinstalled the database and recreated the data and I still get the bug. I do not think that this is fixed!

Please repeat exactly the following steps to check if we still have a bug:

1. Login as Admin
2. Create a location, opening hours, a bike and slots for that bike.
3. Logout
4. Login as Author
5. Go to Commons Booking/Items

Result: 
a) I can see the bike, even though I am only logged in as author and have not created the bike.
b) `Uncaught Error: Call to a member function usage_multiple()`

**Comment by flegfleg** [comment]
Hi @christianvoigt i could not reproduce the error, either. 
Could you reproduce it on dev?

**Comment by christianvoigt** [comment]
What do you mean by dev?

**Comment by flegfleg** [comment]
Cbdev Server

**Comment by christianvoigt** [comment]
Ok, I have used the nuclear option (completely removed the plugin folder and cloned it again from the git repo). Now the error is gone. So it seems as if I had not the most recent commits even though I did use "git pull" several times and it told me that the repository was already up to date. Don't know what happened. Let's hope this does not happen again.
