### ISSUE TITLE
Admin-Interface ausblenden (Suche, Bulk-Action, Filter) in Item, Locations & Bookings

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commons-booking-2#552]
<img width="1298" alt="Bildschirmfoto 2020-02-07 um 17 04 46" src="https://user-images.githubusercontent.com/4009931/74044870-1607fe00-49cc-11ea-8044-6c31c7a10245.png">

- [x] Location
- [x] Item
- [x] Bookings

**Comment by flegfleg** [comment]
Auf der Bookings-Seite ist noch nichts ausgeblendet,  @markus-mw arbeitet  ja da noch dran.
