### ISSUE TITLE
Deleting single slots bugs

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#554]
Deleting a single slot is currently not working correctly 

- [x] A "Delete" deletes all slots

## A) Deleting slot with "delete" on bottom of popup deletes all slots 

1. Create two single slots 
<img width="932" alt="Bildschirmfoto 2020-02-11 um 00 59 43" src="https://user-images.githubusercontent.com/4009931/74202050-aa43c080-4c6b-11ea-84bd-8213f6c6289a.png">

2. Click Delete
<img width="932" alt="Bildschirmfoto 2020-02-11 um 00 59 50" src="https://user-images.githubusercontent.com/4009931/74202104-d101f700-4c6b-11ea-9513-78798bc7968f.png">

3. ALL slots have been deleted

<img width="932" alt="Bildschirmfoto 2020-02-11 um 01 00 04" src="https://user-images.githubusercontent.com/4009931/74202122-da8b5f00-4c6b-11ea-82b7-5e2cbcdf3002.png">

**Comment by flegfleg** [comment]
> Delete should only be deleting the single period. That is a bug. However, it was definitely working when I handed over and thus not my responsibility at the moment.
All these actions can be followed through easily in the do_action architecture.

**Comment by markus-mw** [comment]
@flegfleg Das löschen von einzelnen Posts ist bisher überhaupt nicht vorgesehen. Sie lässt sich jedoch recht einfach umsetzen, führt aber auch dazu, dass das Backend nicht mehr klar kommt, weil diese Situation an verschiedenen Stellen zu Fehlern führt. Ich versuche mal alle problematischen Stellen ausfindig zu machen und die Fehler abzufangen.

**Comment by flegfleg** [comment]
@markus-mw sprechen wir vom selben? 
Also aus einer sich wiederholenden perioddefinition eine raus löschen? 

<img width="932" alt="74202104-d101f700-4c6b-11ea-9513-78798bc7968f" src="https://user-images.githubusercontent.com/4009931/74572275-23e6f180-4f7f-11ea-9714-fe8da37e6507.png">

**Comment by markus-mw** [comment]
@flegfleg Ja, genau. Habe aber auch gerade festgestellt, dass ich noch eine Ebene tiefer gehen muss, um den einzelnen Eintrag zu erwischen...
