### ISSUE TITLE
Backend opening hours popup hängt nach Klick auf "save", speichert aber im Hintergrund trotzdem:

### ISSUE THREAD

**Issue by farbschein** [wielebenwir/commons-booking-2#560]
https://miro.com/app/board/o9J_kv8Db5U=/?moveToWidget=3074457347248071634

**Comment by flegfleg** [comment]
Kann ich aktuell nicht reproduzieren.

**Comment by flegfleg** [comment]
ich glaube das ist gelöst, falls es noch mal auftreten sollte: genauer beschreiben bitte :)
