### ISSUE TITLE
Kalender-Hinweise beim Paging nicht verständlich bzw. Übersetzungsfehler

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commons-booking-2#629]
https://miro.com/app/board/o9J_kv8Db5U=/?moveToWidget=3074457347389989682&cot=3

**Comment by farbschein** [comment]
@hanneskasimir Soweit möglich sprachlich angepasst. Nochmal kärung, wann diese Meldung überhaupt auftaucht.
