### ISSUE TITLE
hooks 

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#68]
do_action() 

* plugin data change, 
* booking made,
 location change etc.

 for velo-integration push notifications (in separate plugin)

possible duplicate #61

**Comment by anewholm** [comment]
search codebase for do_action() to see current action hooks.
cb2_data_changed is implemented
all wordpress hooks are implemented, e.g. save_periodentity_user_post, save_post, etc.
additional OO custom_hooks() are implemented, e.g. cb2_save_post_booked
$post_before is not working at the moment. It shows the post values before the update thus allowing the programmer to detect what has changed.

**Comment by flegfleg** [comment]
👍  Though looking through the code and the documentation, i don't immediately see how to use the following hooks (to be used by the email system):

* booking_created
* booking_canceled

sorry, i need some more info :)
