### ISSUE TITLE
Pretty permalinks warning disappears even if permalink structure is not changed to "post name"

### ISSUE THREAD

**Issue by christianvoigt** [wielebenwir/commons-booking-2#70]
Currently, only the format "Post name" (http://localhost/sample-post/) works with CB2, not the other "pretty formats". But the CB2 warning disappears as soon as a pretty format is selected.

CB2 should warn the user that "Post name" has to be selected. This warning should only disappear if the permalink structure was changed to "Post name".

Alternatively, CB2 should support the other pretty formats as well.

**Comment by flegfleg** [comment]
test: try different permalinks settings, flush permalinks
