### ISSUE TITLE
Tab system in post-edit.php to maximise calendar screen space. & admin bar meta-box setting

### ISSUE THREAD

**Issue by anewholm** [wielebenwir/commons-booking-2#84]

**Comment by flegfleg** [comment]
I implement tabs for the settings that you can re-use 
(I will add conditionals)

**Comment by flegfleg** [comment]
tabs implemented in https://github.com/wielebenwir/commons-booking-2/blob/master/admin/includes/CB2_Admin_Tabs.php

see https://github.com/wielebenwir/commons-booking-2/blob/dd1fa8c63a7977cf91fdcff8507337e88e918055/admin/includes/CB2_Enqueue_Admin.php#L43
